site_name: Python CDMX
site_description: Comunidad de desarrolladores Python en la Ciudad de México
site_author: Comunidad Python CDMX
site_url: https://pythoncdmx.org

# Repository
repo_name: PythonMexico/pythonCDMX
repo_url: https://github.com/PythonMexico/pythonCDMX/
#edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Python CDMX

# Theme configuration
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico

  # Custom colors based on logo
  palette:
    # Light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  # Features - configuración optimizada
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Icons
  icon:
    repo: fontawesome/brands/github


# Plugins
plugins:
  - search:
      lang: es
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      timezone: America/Mexico_City
      locale: es
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - awesome-nav

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PythonMexico/pythonCDMX
      name: GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/PythonCDMX
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/PythonMexico
      name: Twitter/X
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@PythonMexico
      name: YouTube
    - icon: fontawesome/brands/meetup
      link: https://www.meetup.com/python-mexico
      name: Meetup
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/pythoncdmx/
      name: Instagram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/13126454/
      name: LinkedIn


# Custom CSS and JavaScript
extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: En esta página
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: PythonMexico
      repo: pythonCDMX
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Validation
validation:
  nav:
    omitted_files: ignore
    not_found: warn
  links:
    not_found: warn
