name: Build and Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    name: Build and Validate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

      - name: Build with MkDocs
        run: mkdocs build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for broken links
        run: |
          # Iniciar mkdocs serve en background (mejor que python -m http.server)
          mkdocs serve -a 127.0.0.1:8000 &
          sleep 15  # Dar más tiempo para que mkdocs serve esté listo

          # Ejecutar check de links
          python scripts/check_links.py

          # Verificar resultado
          broken_count=$(jq '.summary.broken_links' broken_links.json)

          if [ "$broken_count" -gt 0 ]; then
            echo "❌ Found $broken_count broken links - failing!"
            pkill -f "mkdocs serve" || true
            exit 1
          fi

          echo "✅ All links working!"
          pkill -f "mkdocs serve" || true

      # Solo para main: guardar el sitio construido
      - name: Upload build artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
          retention-days: 1
